---
- name: Setup k3s
  ansible.builtin.include_tasks: k3s.yml

- name: Setup PostgreSQL
  ansible.builtin.include_tasks: postgres.yml

- name: Deploy application
  ansible.builtin.include_tasks: deploy.yml
